<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email confirmation</title>
</head>
<body>
<h1 style="color: blue"> Confirmation of registration</h1>
<#--<h4 style="color: green"> Подтверждение регистрации</h4>-->
<#--<h2> Добрый день, ${firstName} ${lastName}</h2>-->
<#--<p> для подтверждения регистрации пройдите по <a href="${link}"> ссылке </a> </p>-->
<h2> Good afternoon, ${firstName} ${lastName}</h2>
<p> to confirm your registration, follow the <a href="${link}"> link </a> </p>
</body>
</html>
